### ISSUE TITLE
License for go-virtualbox?

### ISSUE THREAD

**Issue by asnowfix** [riobard/go-virtualbox#5]
Hello @riobard , what is the license of this repository? Reason for me to ask is that I added some code (mostly for my own ramp-up in GoLang) & am willing to turn on CI using TravisCI, CircleCI or both. Both of them require that the code has a license. In case you are in doubt I would personally suggest BSD-ish (such as X11/MIT/BSD, like [GoLang itself](https://github.com/golang/go/blob/master/LICENSE) ) or [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0). TIA for your response.

**Comment by riobard** [comment]
Apache 2.0! https://github.com/riobard/go-virtualbox/commit/39b919eb87081c0dbf971b3a86c62c288facf1e8
